services:
  db:
    image: postgres:16-alpine
    command: >
      postgres 
      -c shared_preload_libraries=pg_stat_statements
      -c track_activity_query_size=4096
      -c track_io_timing=on
      -c pg_stat_statements.track=ALL
    labels:
      com.datadoghq.ad.check_names: '["postgres"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: |
        [{
          "dbm": true,
          "host": "db",
          "port": 5432,
          "username": "datadog",
          "password": "datadog",
          "dbname": "memoapp",
          "collect_raw_query_statement": {
            "enabled": true
          }
        }]
    environment:
      POSTGRES_DB: memoapp
      POSTGRES_USER: memo
      POSTGRES_PASSWORD: memo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memo -d memoapp"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs  # 로그 파일 저장 경로 
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: memoapp
      DB_USER: memo
      DB_PASSWORD: memo
      WEATHER_API_KEY: 390a860c8b4747b681321954263003
      DD_ENV: prd
      DD_SERVICE: memo-app
      DD_VERSION: 1.0.4
      DD_PROFILING_ENABLED: true
      DD_DYNAMIC_INSTRUMENTATION_ENABLED: true
      DD_DBM_PROPAGATION_MODE: full
      DD_DBM_TRACE_PREPARED_STATEMENTS: true
      DD_CODE_ORIGIN_FOR_SPANS_ENABLED: true
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
